### ISSUE TITLE
Problems running with both OpenJDK, Zulu JDK versions 8-14 with necessary OpenJFX dependencies on Ubuntu Linux 16.04

### ISSUE THREAD

**Issue by GeorgeWood2** [Naton1/Graphical-Client-Starter#1]
Hi guys,

I'm currently getting this error in my terminal despite having the necessary JavaFX dependencies (yes I know it was deprecated in versions post Java 8).

I run this command to grab the necessary dependencies:

java --module-path /usr/share/openjfx/lib --add-modules=javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web -jar GraphicalClientStarter.jar 

This grabs the JavaFX dependencies and works with other programs using JavaFX.

But I get this:

java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private static float javafx.scene.text.Font.defaultSystemFontSize accessible: module javafx.graphics does not "opens javafx.scene.text" to unnamed module @2d209079
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:349)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:289)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:174)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:168)
	at starter.GraphicalClientStarter.overrideDefaultFont(GraphicalClientStarter.java:56)
	at starter.GraphicalClientStarter.main(GraphicalClientStarter.java:42)
	... 11 more
Exception running application starter.GraphicalClientStarter

Am I missing something simple? Plz halp. Much appreciated. <3

**Comment by Naton1** [comment]
The above logs looks like you are running something newer than java 8. I'm not sure if it will work with anything other than java 8 (I honestly haven't tried). The issue you are currently experiencing may possibly be resolved by adding `--add-opens javafx.graphics/javafx.scene.text=ALL-UNNAMED` to the launch command after typing java but I really recommend using java 8.

**Comment by GeorgeWood2** [comment]
Sweet, that seems to have it launched! Thank you for the assistance. I tried running it with a Java 8 based OpenJDK version but without that line, it didn't work! Love the software by the way, very very useful :100:

**Comment by Naton1** [comment]
Glad to hear it!
